title: Greybeard Scripting PowerShell Docs
description: Sample documentation for PowerShell scripts using GitHub Pages
theme: jekyll-theme-minimal

# Use custom head include for CSS
include:
	- assets/css/style.scss

plugins:
	- jekyll-include-cache

# For custom head
defaults:
	- scope:
			path: ""
		values:
			head: head-custom.html