title: Greybeard Docs
description: PowerShell General Documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greybeard-scripting.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: just-the-docs

url: https://just-the-docs.github.io

# Aux links for the upper right navigation
aux_links:
  "PowerShell Universal":
    - "https://powershelluniversal.com/"
  "Docs Repo":
    - "https://github.com/Greybeard-Scripting/greybeard-scripting.github.io"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"