title: Greybeard Docs
description: PowerShell General Documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greybeard-scripting.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: just-the-docs

url: https://just-the-docs.github.io

# Aux links for the upper right navigation
aux_links:
  "PowerShell Universal":
    - "https://powershelluniversal.com/"
  "Docs Repo":
    - "https://github.com/Greybeard-Scripting/greybeard-scripting.github.io"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Greybeard-Scripting/greybeard-scripting.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately  