title: Greybeard Scripting PowerShell Docs
description: Sample documentation for PowerShell scripts using GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Use custom head include for CSS
include:
	- assets/css/style.scss

plugins:
	- jekyll-include-cache

# For custom head
defaults:
	- scope:
			path: ""
		values:
			head: head-custom.html