on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  jekyll-build:
    name: Build (jekyll gem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: false
      - name: Bundle Install (Jekyll 4.3)
        run: bundle install
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-4.3
      - name: Init Search
        run: bundle exec rake search:init
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-4.3
      - name: Build Site
        run: bundle exec jekyll build
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-4.3

  github-pages-build:
    name: Build (github-pages gem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: false
      - name: Bundle Install
        run: bundle install
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-github-pages
      - name: Build Site
        run: bundle exec jekyll build
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-github-pages

  validate:
    name: Validate HTML
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.4"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v4
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
      - name: Build Site
        run: bundle exec jekyll build
      - name: Test with Nu Validator
        uses: Cyb3r-Jak3/html5validator-action@8c6ac0aa42df299c0322ce9980fed61c10930a66
        with:
          config: fixtures/html5validator-config.yml
      - name: Test with html-proofer
        run: bundle exec htmlproofer _site --disable-external
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

  assets:
    name: Test CSS and JS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
